In [2]:
import sys
sys.path.append("/anaconda/envs/azureml_py38/lib/python3.8/site-packages")

In [3]:
import psycopg2
import pandas as pd
import numpy as np

In [4]:
def get_db_cursor():
    username = "doadmin"
    password = 'yzmodwh2oh16iks6'
    host = 'db-postgresql-cl1-do-user-2276924-0.db.ondigitalocean.com'
    port = 25060
    database = 'MandatoryMetadata'
    schema = 'historical'

    conn = psycopg2.connect(host=host, database=database,
                            user=username, password=password, port=port)
    cur = conn.cursor()
    cur.execute("SET search_path TO " + schema)

    return conn, cur

In [5]:
conn, cur = get_db_cursor()

In [6]:
v1_samples = pd.read_csv('./outputFiles/spectra.csv',usecols=[0])

In [7]:
v1_samples

             Unnamed: 0
0      AGD207-408SA0706
1      AGD207-431SA0001
2      AGD207-431SA0002
3      AGD207-431SA0003
4      AGD207-431SA0004
...                 ...
87362       CW017SA7164
87363       CW017SA7167
87364       CW017SA7168
87365       CW104SA0052
87366       CW104SA0053

[87367 rows x 1 columns]

In [8]:
v2_samples = pd.read_sql('select sample_code from MandatoryMetadata', con = conn)

/tmp/ipykernel_17899/2923516565.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  v2_samples = pd.read_sql('select sample_code from MandatoryMetadata', con = conn)

In [9]:
v2_samples

        sample_code
0         ML-SS21-2
1         ML-SS21-2
2         ML-SS21-2
3         ML-SS21-2
4         ML-SS21-2
...             ...
186365  CZ033SA0175
186366  CS728SA0001
186367  CA002SA0720
186368  CA002SA0718
186369  CT003SA0072

[186370 rows x 1 columns]

In [10]:
v2_samples = v2_samples.loc[~v2_samples['sample_code'].isin(v1_samples['Unnamed: 0'])]

In [11]:
v2_samples

        sample_code
0         ML-SS21-2
1         ML-SS21-2
2         ML-SS21-2
3         ML-SS21-2
4         ML-SS21-2
...             ...
186365  CZ033SA0175
186366  CS728SA0001
186367  CA002SA0720
186368  CA002SA0718
186369  CT003SA0072

[77818 rows x 1 columns]

In [12]:
sample_codes = v2_samples['sample_code'].values

In [13]:
if(len(sample_codes) < 5000):
    count  = len(sample_codes)
    step=count
elif(len(sample_codes) < 70000):
    count = len(sample_codes)
    step=5000
else:
    count = 70000
    step=5000
start = 0

In [14]:
count

70000

In [15]:
start

0

In [16]:
step

5000

In [17]:
spectra = pd.DataFrame()

In [18]:
def convertSpectra(df):
    print("Converting spectra")
    df_ = pd.DataFrame([i[[i for i in i.keys()][0]] for i in df['averaged_spectra'].values],columns = np.arange(522,3977,2))
    df_.index = df.index
    print("Spectra converted")
    return df_

In [19]:
for i in np.arange(start, count, step):
        
    print("Fetching spectra from {}".format(start))
    samples = [i for i in sample_codes][start:start+step]
    print(len(samples))
    query = f"SELECT spectraldata.metadata_id, spectraldata.averaged_spectra, mandatorymetadata.sample_code FROM spectraldata INNER JOIN mandatorymetadata ON mandatorymetadata.metadata_id = spectraldata.metadata_id WHERE averaged=True AND sample_code IN {str(samples).replace('[','(').replace(']',')')}"

    _ = pd.read_sql(query, con=conn)
    print("This is the spectra",_)
    spectra = pd.concat([spectra, _], axis=0)
    start = start + step
    if (count-step) > 5000:
        step=5000
    else:
        step = count-step

Fetching spectra from 0
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          187075  {'521': [2.307263405435277, 2.3483773245548107...
1          186966  {'522': [2.397271446121614, 2.4282403701836808...
2          186768  {'521': [2.3837186661571783, 2.426691483682147...
3          186864  {'521': [2.2609804305624883, 2.293829992699927...
4          186863  {'522': [2.3808439217120956, 2.408734106733358...
...           ...                                                ...
6206       161700  {'522': [2.360054879422215, 2.302488578286381,...
6207       161726  {'522': [2.400198791126645, 2.4553677734575245...
6208       161730  {'522': [2.503719823794537, 2.5818505003199634...
6209       161766  {'522': [2.242610077256419, 2.2293044933304005...
6210       161777  {'522': [2.32940209441737, 2.2779935330976473,...

          sample_code
0           ML-SS21-1
1           ML-SS21-1
2           ML-SS21-1
3           ML-SS21-1
4           ML-SS21-1
...               ...
6206   FA419-76SA0001
6207   FA539-22SA0001
6208      CA053SA1351
6209  FA807-778SA0003
6210  AGD218-99SA0002

[6211 rows x 3 columns]
Fetching spectra from 5000
5000
This is the spectra        metadata_id                                   averaged_spectra  \
0           187075  {'521': [2.307263405435277, 2.3483773245548107...
1           187056  {'522': [2.3645274701916428, 2.380267433090121...
2           187043  {'522': [2.3943149118512363, 2.391047759744343...
3           187025  {'522': [2.381931136382427, 2.383939558800457,...
4           186987  {'521': [2.243089700678383, 2.1948415943304833...
...            ...                                                ...
14484       164290  {'522': [2.293147234336991, 2.2899005801815067...
14485       164302  {'522': [2.2473573448899007, 2.255195699005539...
14486       164312  {'522': [2.050560245127239, 2.035885551596273,...
14487        11074  {'522': [2.439012542140077, 2.3931823230010574...
14488       164323  {'522': [2.310717799019555, 2.357101216642394,...

          sample_code
0           ML-SS21-1
1           ML-SS21-1
2           ML-SS21-1
3           ML-SS21-1
4           ML-SS21-1
...               ...
14484     CT214SA0617
14485     CT214SA0628
14486     CT214SA0621
14487  FA537-91SA0001
14488  FA537-93SA0002

[14489 rows x 3 columns]
Fetching spectra from 10000
5000
This is the spectra        metadata_id                                   averaged_spectra  \
0            10080  {'522': [2.274885254503441, 2.2319242103001766...
1            10047  {'522': [2.278888888660214, 2.297786508344143,...
2            13692  {'522': [1.8475415838865055, 1.901551774140139...
3             8997  {'522': [2.300421448843487, 2.3375871951902756...
4            10093  {'522': [2.2795946619414096, 2.273787762387321...
...            ...                                                ...
16716        11536  {'522': [1.74404657343899, 1.7219717096808616,...
16717        11537  {'522': [2.2543427913428813, 2.23920650446992,...
16718        12880  {'522': [2.17262980577792, 2.1612774758742392,...
16719        11538  {'522': [2.272784491759387, 2.2368417866791614...
16720        11539  {'522': [2.013983522279056, 1.9928827493859576...

           sample_code
0      AGD918-20SA0001
1      AGD918-34SA0002
2          CB206SA0101
3      AGD918-82SA0004
4      AGD918-35SA0001
...                ...
16716   AGD901-4SA0004
16717  AGD918-50SA0001
16718      CA330SA2324
16719  AGD918-78SA0001
16720   AGD917-5SA0002

[16721 rows x 3 columns]
Fetching spectra from 15000
5000
This is the spectra        metadata_id                                   averaged_spectra  \
0           187075  {'521': [2.307263405435277, 2.3483773245548107...
1           187056  {'522': [2.3645274701916428, 2.380267433090121...
2           187043  {'522': [2.3943149118512363, 2.391047759744343...
3           187025  {'522': [2.381931136382427, 2.383939558800457,...
4           186987  {'521': [2.243089700678383, 2.1948415943304833...
...            ...                                                ...
16724       161180  {'522': [2.3265568598179995, 2.264019334904624...
16725       161182  {'522': [2.3783419198610103, 2.422783456084052...
16726       161392  {'522': [2.33595944594112, 2.3252500220468213,...
16727       161208  {'522': [2.317288846451495, 2.3108945112643537...
16728       161217  {'522': [2.3213938332848225, 2.414833891653165...

      sample_code
0       ML-SS21-1
1       ML-SS21-1
2       ML-SS21-1
3       ML-SS21-1
4       ML-SS21-1
...           ...
16724   ML-SS21-1
16725   ML-SS21-1
16726   ML-SS21-1
16727   ML-SS21-1
16728   ML-SS21-1

[16729 rows x 3 columns]
Fetching spectra from 20000
5000
This is the spectra        metadata_id                                   averaged_spectra  \
0            22662  {'522': [2.158945932015736, 2.153889578143777,...
1            10047  {'522': [2.278888888660214, 2.297786508344143,...
2            10093  {'522': [2.2795946619414096, 2.273787762387321...
3            10080  {'522': [2.274885254503441, 2.2319242103001766...
4             8028  {'522': [2.4709494644009036, 2.472236042557176...
...            ...                                                ...
15799         9011  {'522': [2.410298474693552, 2.4020397120511037...
15800         9013  {'522': [2.4814217534016754, 2.458529288858571...
15801        12801  {'522': [1.995790882248075, 1.9721684804561743...
15802         9128  {'522': [2.474892988471389, 2.458521552105081,...
15803        12810  {'522': [2.0956831689507207, 2.094727540187541...

           sample_code
0          CF177SA1467
1      AGD918-34SA0002
2      AGD918-35SA0001
3      AGD918-20SA0001
4      AGD903-36SA0002
...                ...
15799  AGD918-23SA0004
15800  AGD918-74SA0003
15801      CA330SA2163
15802   AGD903-37A0001
15803      CA330SA2036

[15804 rows x 3 columns]
Fetching spectra from 25000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          187075  {'521': [2.307263405435277, 2.3483773245548107...
1          187056  {'522': [2.3645274701916428, 2.380267433090121...
2          187043  {'522': [2.3943149118512363, 2.391047759744343...
3          187025  {'522': [2.381931136382427, 2.383939558800457,...
4          186987  {'521': [2.243089700678383, 2.1948415943304833...
...           ...                                                ...
9377       161735  {'522': [2.359731449123168, 2.4714294774879737...
9378       161753  {'522': [2.260372011337533, 2.302202772227119,...
9379       161767  {'522': [2.4079214978472976, 2.361045826196156...
9380       161773  {'522': [2.278073481381654, 2.288160863047489,...
9381       161780  {'522': [2.33516306388488, 2.2543873074679697,...

          sample_code
0           ML-SS21-1
1           ML-SS21-1
2           ML-SS21-1
3           ML-SS21-1
4           ML-SS21-1
...               ...
9377   FA419-86SA0002
9378  AGD928-28SA0002
9379      CA053SA1409
9380  AGD928-28SA0003
9381      CA053SA1404

[9382 rows x 3 columns]
Fetching spectra from 30000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          107164  {'522': [2.0718084080978603, 2.029311660335484...
1           95749  {'522': [2.150865347248802, 2.194643888298641,...
2          107165  {'522': [2.160624560592213, 2.2155427941949903...
3          107166  {'522': [2.2008846455956173, 2.321818253785458...
4          107158  {'522': [2.3111737718971295, 2.382890145174427...
...           ...                                                ...
5032       161069  {'522': [2.20023299426236, 2.3282682578031437,...
5033       161075  {'522': [2.0011840779884444, 2.048553508212463...
5034       161091  {'522': [2.3138144462069095, 2.29630994870248,...
5035       161093  {'522': [1.9405733118056636, 1.955378765696380...
5036       161094  {'522': [2.081532391008924, 2.044332592554879,...

         sample_code
0     I30-1-35SA0035
1        CH006SA5417
2     I30-1-14SA0329
3     I30-1-13SA0048
4     I30-1-36SA0028
...              ...
5032     CH006SA2879
5033     CS417SA0046
5034     CK013SA2039
5035     CF131SA0921
5036     CF131SA0268

[5037 rows x 3 columns]
Fetching spectra from 35000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          108481  {'522': [2.213952400982423, 2.2079233961619673...
1          108482  {'522': [2.2156362012611166, 2.163811121193387...
2          108483  {'522': [2.1485826268196626, 2.157922033484391...
3          108484  {'522': [2.4265925637629326, 2.408174292090732...
4          108485  {'522': [1.945060412024369, 1.9306223663312543...
...           ...                                                ...
5003       109621  {'522': [2.1577872042423856, 2.250000730464194...
5004       109624  {'522': [2.2780775035532645, 2.378666269312538...
5005       161092  {'522': [2.0437636452011354, 2.099161232875365...
5006       161100  {'522': [2.0924970358907853, 1.884085295381002...
5007       161077  {'522': [2.180050505253619, 2.1816515651034107...

          sample_code
0      I30-1-10SA0171
1      I30-1-30SA0004
2      I30-1-14SA0069
3      FA419-31SA0003
4      I30-1-20SA0013
...               ...
5003   FA617-70SA0001
5004   AGD837-7SA0002
5005    FA222-9SA0001
5006  AGD806-42SA0001
5007   I30-1-12SA0065

[5008 rows x 3 columns]
Fetching spectra from 40000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          119305  {'522': [2.1636099908177058, 2.141558655219781...
1          119302  {'522': [2.306427851914301, 2.3335228032143593...
2          119303  {'522': [1.776712558387745, 1.7723418431684412...
3          119642  {'522': [2.2046795909905708, 2.217654966860105...
4          119301  {'522': [1.953391926426997, 1.9449189164277243...
...           ...                                                ...
4996       124325  {'522': [2.2723891231604867, 2.286408191276184...
4997       124329  {'522': [1.9688415049291201, 1.967748264137951...
4998       124330  {'522': [2.0893625491404793, 2.065115638085085...
4999       124333  {'522': [2.2017550565237, 2.155568811266905, 2...
5000       161088  {'522': [1.9453473671406885, 2.007683530660661...

      sample_code
0     CT214SA0574
1     CS331SA0017
2     CS436SA0037
3     CS158SA0696
4     CO126SA0229
...           ...
4996  CS196SA0314
4997  CS387SA0022
4998  CO126SA0020
4999  CS255SA0017
5000  CS341SA0083

[5001 rows x 3 columns]
Fetching spectra from 45000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          150627  {'522': [1.8741000391633091, 1.854811524701267...
1          150635  {'522': [2.0295687282584756, 2.047287084002841...
2          150654  {'522': [2.3090340211786784, 2.367327177415693...
3          150637  {'522': [2.3244015368711626, 2.331899248075591...
4          150647  {'522': [2.446750161340474, 2.421800730810803,...
...           ...                                                ...
5014       148212  {'522': [2.180551188961456, 2.1830329189178066...
5015       148215  {'522': [2.2643832231995376, 2.204506402666383...
5016       148217  {'522': [2.1821980721957104, 2.223808003051809...
5017       148225  {'522': [2.2923505446407955, 2.306257862536566...
5018       148232  {'522': [2.326163598294154, 2.3837462388644495...

      sample_code
0     CM073SA0783
1     CK079SA3435
2     CK099SA0755
3     CM022SA0185
4     CN074SA0363
...           ...
5014   CV06SA0263
5015  CK079SA4154
5016  CO027SA2507
5017  CO027SA1867
5018  CN074SA0323

[5019 rows x 3 columns]
Fetching spectra from 50000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          187075  {'521': [2.307263405435277, 2.3483773245548107...
1          187056  {'522': [2.3645274701916428, 2.380267433090121...
2          187043  {'522': [2.3943149118512363, 2.391047759744343...
3          187025  {'522': [2.381931136382427, 2.383939558800457,...
4          186987  {'521': [2.243089700678383, 2.1948415943304833...
...           ...                                                ...
7258       160634  {'522': [2.2758675112562066, 2.260327478144987...
7259       160635  {'522': [2.187786380432961, 2.2337255468075257...
7260       160636  {'522': [2.310914035896638, 2.2263296772083967...
7261       160640  {'522': [2.214097869530992, 2.1897408582819846...
7262       160647  {'522': [2.4257752753397943, 2.456430060629887...

      sample_code
0       ML-SS21-1
1       ML-SS21-1
2       ML-SS21-1
3       ML-SS21-1
4       ML-SS21-1
...           ...
7258  CD027SA0010
7259  CE006SA2167
7260  CA330SA1506
7261  CE006SA2191
7262  CB048SA0031

[7263 rows x 3 columns]
Fetching spectra from 55000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          187075  {'521': [2.307263405435277, 2.3483773245548107...
1          187056  {'522': [2.3645274701916428, 2.380267433090121...
2          187043  {'522': [2.3943149118512363, 2.391047759744343...
3          187025  {'522': [2.381931136382427, 2.383939558800457,...
4          186987  {'521': [2.243089700678383, 2.1948415943304833...
...           ...                                                ...
5647       166409  {'522': [2.283813863204471, 2.3075538425049205...
5648       166410  {'522': [2.3530392626345105, 2.351563729181086...
5649       166411  {'522': [2.592178092078873, 2.585046414559575,...
5650       166412  {'522': [2.3788438912743652, 2.490984243916541...
5651       166413  {'522': [2.3847762623423345, 2.327278591409487...

          sample_code
0           ML-SS21-1
1           ML-SS21-1
2           ML-SS21-1
3           ML-SS21-1
4           ML-SS21-1
...               ...
5647  AGD917-64SA0001
5648      CC029SA1544
5649      CA053SA1462
5650      CA053SA1461
5651      CT353SA0007

[5652 rows x 3 columns]
Fetching spectra from 60000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0              27  {'522': [2.168894010369754, 2.1714387890354905...
1          177019  {'522': [2.4472335850461935, 2.416163524666181...
2          177197  {'522': [2.413664708747909, 2.420136196041784,...
3          177145  {'521': [2.4040616420390135, 2.554046932102097...
4          177310  {'522': [2.4069673682368773, 2.424975993032607...
...           ...                                                ...
5271       166286  {'522': [2.3606444358719307, 2.380182037365423...
5272       166313  {'522': [2.3056139483569456, 2.363762461923298...
5273       166315  {'522': [2.390028102810339, 2.4124151078339784...
5274       166322  {'522': [2.4388540744492473, 2.399392737899509...
5275       166414  {'522': [2.249738603378021, 2.2770500845432853...

     sample_code
0      ML-SS21-8
1      ML-SS21-5
2      ML-SS21-5
3      ML-SS21-5
4      ML-SS21-3
...          ...
5271   ML-SS21-3
5272   ML-SS21-3
5273   ML-SS21-3
5274   ML-SS21-3
5275   ML-SS21-3

[5276 rows x 3 columns]
Fetching spectra from 65000
5000
This is the spectra       metadata_id                                   averaged_spectra  \
0          187075  {'521': [2.307263405435277, 2.3483773245548107...
1          187056  {'522': [2.3645274701916428, 2.380267433090121...
2          187043  {'522': [2.3943149118512363, 2.391047759744343...
3          187025  {'522': [2.381931136382427, 2.383939558800457,...
4          186987  {'521': [2.243089700678383, 2.1948415943304833...
...           ...                                                ...
5710       166389  {'522': [2.477091493551886, 2.414741370768122,...
5711       166414  {'522': [2.249738603378021, 2.2770500845432853...
5712       166326  {'522': [2.494333709674491, 2.5194716828400674...
5713       166338  {'522': [2.431711745778313, 2.491956221424079,...
5714       166368  {'522': [2.3832986618691603, 2.418019421881964...

     sample_code
0      ML-SS21-1
1      ML-SS21-1
2      ML-SS21-1
3      ML-SS21-1
4      ML-SS21-1
...          ...
5710   ML-SS21-3
5711   ML-SS21-3
5712   ML-SS21-3
5713   ML-SS21-3
5714   ML-SS21-3

[5715 rows x 3 columns]

/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)
/tmp/ipykernel_17899/1108552379.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _ = pd.read_sql(query, con=conn)

In [20]:
spectra = spectra.set_index("sample_code")

In [51]:
conn.close()

In [52]:
spectra = spectra.set_index('sample_code')

In [21]:
spectra = convertSpectra(spectra)


spectra.to_csv("./outputFiles/spectraldata.csv")

Converting spectra
Spectra converted

In [21]:
spectra

,522,524,526,528,530,532,534,536,538,540,...,3958,3960,3962,3964,3966,3968,3970,3972,3974,3976
0,2.364527,2.380267,2.415282,2.431268,2.441101,2.462991,2.473978,2.428879,2.422211,2.447353,...,1.170164,1.170703,1.170675,1.170313,1.170076,1.169900,1.169492,1.168838,1.168238,1.167781
1,2.324680,2.324753,2.373763,2.411027,2.402217,2.347667,2.317289,2.338107,2.375101,2.368011,...,1.149651,1.149604,1.149459,1.148917,1.148238,1.147781,1.147594,1.147623,1.147640,1.147664
2,2.397271,2.428240,2.399225,2.358932,2.332269,2.308703,2.294938,2.292284,2.298963,2.309691,...,1.160591,1.160070,1.159524,1.159550,1.159486,1.158533,1.157588,1.157537,1.157760,1.157822
3,2.394315,2.391048,2.357433,2.361828,2.380389,2.410625,2.426476,2.401460,2.370650,2.361235,...,1.152852,1.152934,1.152444,1.151799,1.151322,1.150696,1.150411,1.150530,1.150366,1.150150
4,2.381931,2.383940,2.376204,2.340311,2.348089,2.348603,2.345284,2.341323,2.328165,2.294485,...,1.159744,1.158565,1.157161,1.156499,1.156687,1.156656,1.155951,1.155213,1.154969,1.155184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5709,2.431712,2.491956,2.525230,2.497294,2.461680,2.457347,2.479673,2.508331,2.492839,2.441814,...,1.129957,1.129489,1.128628,1.128164,1.128154,1.128244,1.128160,1.127920,1.127710,1.127501
5710,2.383299,2.418019,2.405626,2.382745,2.379580,2.403409,2.391373,2.320085,2.273765,2.275257,...,1.149114,1.149265,1.149298,1.148614,1.147901,1.148023,1.148273,1.148000,1.147757,1.147768
5711,2.388890,2.350033,2.309996,2.327226,2.352492,2.330514,2.316581,2.350303,2.387681,2.412264,...,1.171154,1.170969,1.170589,1.170483,1.170664,1.170294,1.169510,1.169155,1.169263,1.169555
5712,2.477091,2.414741,2.403005,2.449703,2.481381,2.444921,2.382814,2.372414,2.406186,2.411119,...,1.161688,1.161186,1.160171,1.159406,1.159063,1.158751,1.158270,1.157872,1.157729,1.157586
5713,2.249739,2.277050,2.323580,2.344774,2.365736,2.380376,2.383867,2.385747,2.372978,2.342873,...,1.167203,1.167368,1.167123,1.166785,1.166569,1.166275,1.166020,1.165878,1.165542,1.164923

In [22]:
import pandas as pd
spectra= pd.read_csv("outputFiles/spectraldata.csv",usecols=[0])
len(spectra)

123300

In [24]:
len(np.unique(spectra.index))

50265

In [27]:
start = 0 
stop = 5000
for n in np.arange(start, (19000), 5000):
    print(n)

0
5000
10000
15000

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('outputFiles/PCC_Classes/aluminium.csv')

In [6]:
preds = pd.read_csv("outputFiles/predictions/DLv2.2/aluminium_preds.csv")

In [7]:
preds

       sample_code          0
0        ML-SS21-1  845.05840
1        ML-SS21-1  930.48130
2        ML-SS21-1  845.21277
3        ML-SS21-1  888.77905
4        ML-SS21-1  907.39136
...            ...        ...
123302   ML-SS21-3  846.77010
123303   ML-SS21-3  893.17316
123304   ML-SS21-3  921.44040
123305   ML-SS21-3  873.87006
123306   ML-SS21-3  907.70240

[123307 rows x 2 columns]

In [8]:
df

,Unnamed: 0,sample_code,aluminium,0,Difference,Actual_PCC,Predicted_PCC,PCC_Class
0,1489,CC176SA5654,1040.0,884.54590,-155.45410,4.0,NaN,NaN
1,1497,CC176SA5627,1120.0,980.52155,-139.47845,4.0,NaN,NaN
2,1523,CC176SA5628,925.0,560.16120,-364.83880,3.0,NaN,NaN
3,1536,CC176SA5652,859.0,871.38885,12.38885,3.0,3.0,0.0
4,1562,CC176SA5641,711.0,763.31380,52.31380,3.0,3.0,0.0
...,...,...,...,...,...,...,...,...
7233,93208,CK002SA1803,1100.0,1066.29250,-33.70750,4.0,4.0,0.0
7234,93220,CK002SA1806,1030.0,1117.54700,87.54700,4.0,4.0,0.0
7235,93393,CK002SA1801,1000.0,1007.66600,7.66600,3.0,3.0,0.0
7236,94931,CJ030SA5678,995.0,1105.27750,110.27750,3.0,4.0,1.0
7237,94941,CJ030SA5679,1140.0,997.91000,-142.09000,4.0,NaN,NaN

In [10]:
comb = pd.merge(df, preds, on='sample_code', how='inner')

In [11]:
comb.loc[comb['PCC_Class'] <= 1]

,Unnamed: 0,sample_code,aluminium,0_x,Difference,Actual_PCC,Predicted_PCC,PCC_Class,0_y
3,1536,CC176SA5652,859.0,871.38885,12.38885,3.0,3.0,0.0,871.38885
4,1562,CC176SA5641,711.0,763.31380,52.31380,3.0,3.0,0.0,763.31380
5,1583,CC176SA5645,520.0,640.46515,120.46515,2.0,2.0,0.0,640.46515
6,1618,CC176SA5647,945.0,863.47784,-81.52216,3.0,3.0,0.0,863.47784
8,1652,CC176SA5650,517.0,572.62830,55.62830,2.0,2.0,0.0,572.62830
...,...,...,...,...,...,...,...,...,...
53456,93206,CK002SA1805,835.0,1046.02430,211.02430,3.0,4.0,1.0,1046.02430
53457,93208,CK002SA1803,1100.0,1066.29250,-33.70750,4.0,4.0,0.0,1066.29250
53458,93220,CK002SA1806,1030.0,1117.54700,87.54700,4.0,4.0,0.0,1117.54700
53459,93393,CK002SA1801,1000.0,1007.66600,7.66600,3.0,3.0,0.0,1007.66600
53460,94931,CJ030SA5678,995.0,1105.27750,110.27750,3.0,4.0,1.0,1105.27750

In [18]:
spectra = pd.read_csv('outputFiles/spectraldata.csv', index_col=0, engine='c')

In [20]:
spectra.loc[spectra.index.isin(comb.loc[comb['PCC_Class'] <= 1]['sample_code'])]

,522,524,526,528,530,532,534,536,538,540,...,3958,3960,3962,3964,3966,3968,3970,3972,3974,3976
sample_code,,,,,,,,,,,,,,,,,,,,,
CC176SA5652,2.154246,2.092609,2.077228,2.101096,2.120622,2.123532,2.127089,2.126469,2.119017,2.109390,...,1.255574,1.254978,1.253972,1.253552,1.253228,1.252433,1.251589,1.250707,1.249439,1.248191
CC176SA5641,2.239911,2.182096,2.130445,2.081945,2.047989,2.055831,2.099324,2.130741,2.105824,2.057918,...,1.132173,1.131954,1.131708,1.131565,1.131205,1.130505,1.129671,1.128951,1.128448,1.128007
CC176SA5645,2.093391,2.111062,2.063969,2.010349,2.003698,2.011247,1.988045,1.952734,1.942120,1.955275,...,1.161763,1.161122,1.160494,1.160462,1.160539,1.159970,1.159012,1.158122,1.157647,1.157516
CC176SA5647,2.042394,2.090577,2.111565,2.067445,2.036329,2.053858,2.076758,2.071446,2.061716,2.063592,...,1.130418,1.129733,1.128900,1.128374,1.128039,1.127651,1.127224,1.126863,1.126352,1.125385
CC176SA5650,2.270940,2.229641,2.189799,2.145278,2.138737,2.172354,2.205997,2.246785,2.261879,2.219524,...,1.179193,1.178446,1.177620,1.176593,1.175882,1.175641,1.175558,1.175543,1.175335,1.174862
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CK002SA1805,2.275789,2.255795,2.238824,2.242241,2.230048,2.199329,2.175204,2.179353,2.180641,2.145780,...,1.286755,1.285515,1.284647,1.284983,1.286087,1.286118,1.284773,1.283282,1.282345,1.281821
CK002SA1803,2.521574,2.443199,2.414373,2.409841,2.420043,2.455131,2.472920,2.451894,2.434731,2.430271,...,1.325941,1.324451,1.324035,1.324074,1.323478,1.322610,1.322125,1.321414,1.320255,1.318866
CK002SA1806,2.634936,2.540841,2.504133,2.537708,2.569144,2.512635,2.449713,2.435081,2.456787,2.475545,...,1.315967,1.315506,1.315423,1.314387,1.312685,1.312006,1.311860,1.311262,1.310908,1.310861
CK002SA1801,2.256602,2.209911,2.207849,2.255901,2.282473,2.260994,2.237024,2.230615,2.243233,2.251016,...,1.287316,1.285974,1.284600,1.284458,1.284501,1.283343,1.282012,1.281556,1.281128,1.280232
CJ030SA5678,2.286045,2.313707,2.327145,2.313697,2.288203,2.267247,2.241009,2.228010,2.225498,2.219569,...,1.332581,1.332294,1.331651,1.331203,1.330385,1.328845,1.327626,1.326900,1.326593,1.326633

In [16]:
spectra.loc[spectra.index.isin(preds['sample_code'])]

Empty DataFrame
Columns: [522, 524, 526, 528, 530, 532, 534, 536, 538, 540, 542, 544, 546, 548, 550, 552, 554, 556, 558, 560, 562, 564, 566, 568, 570, 572, 574, 576, 578, 580, 582, 584, 586, 588, 590, 592, 594, 596, 598, 600, 602, 604, 606, 608, 610, 612, 614, 616, 618, 620, 622, 624, 626, 628, 630, 632, 634, 636, 638, 640, 642, 644, 646, 648, 650, 652, 654, 656, 658, 660, 662, 664, 666, 668, 670, 672, 674, 676, 678, 680, 682, 684, 686, 688, 690, 692, 694, 696, 698, 700, 702, 704, 706, 708, 710, 712, 714, 716, 718, 720, ...]
Index: []

[0 rows x 1728 columns]

In [17]:
spectra

,522,524,526,528,530,532,534,536,538,540,...,3958,3960,3962,3964,3966,3968,3970,3972,3974,3976
AGD207-408SA0706,2.096135,2.074343,2.077232,2.100555,2.109029,2.113436,2.103539,2.076615,2.058088,2.052834,...,1.397774,1.396845,1.396773,1.396401,1.395748,1.395857,1.395875,1.394762,1.394079,1.393831
AGD207-431SA0001,2.154667,2.128691,2.090363,2.061056,2.036317,2.019021,2.018069,2.030793,2.041479,2.035714,...,1.319761,1.319318,1.319803,1.319366,1.317630,1.316362,1.315863,1.315292,1.314809,1.314864
AGD207-431SA0002,2.412217,2.413204,2.360303,2.307860,2.296765,2.316080,2.321781,2.294391,2.270676,2.284707,...,1.306064,1.306364,1.306144,1.305445,1.305173,1.305272,1.304674,1.303443,1.302389,1.301506
AGD207-431SA0003,2.059137,2.093001,2.136247,2.157497,2.152817,2.144714,2.131581,2.108572,2.105603,2.127556,...,1.306060,1.305862,1.305825,1.305172,1.304238,1.303409,1.302201,1.300902,1.300176,1.300167
AGD207-431SA0004,2.279650,2.237250,2.218038,2.231755,2.238702,2.222442,2.208411,2.211492,2.218197,2.235896,...,1.184210,1.183787,1.183616,1.183282,1.182663,1.182083,1.181676,1.181184,1.180578,1.180207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CW017SA7164,2.187465,2.130583,2.079146,2.053846,2.028107,1.993453,1.961532,1.942093,1.952680,1.984957,...,1.150593,1.149948,1.150184,1.150910,1.151015,1.150748,1.150615,1.150541,1.150394,1.149878
CW017SA7167,2.154086,2.122482,2.061072,2.017800,2.007365,2.026743,2.058742,2.077140,2.069497,2.065080,...,1.226464,1.225381,1.224707,1.224440,1.224299,1.224463,1.225003,1.225329,1.224778,1.223832
CW017SA7168,2.159694,2.118398,2.149818,2.189918,2.170442,2.141771,2.140313,2.135926,2.115328,2.103800,...,1.188755,1.188114,1.188517,1.189058,1.188850,1.188428,1.187938,1.187309,1.186815,1.186573
CW104SA0052,1.915089,1.907579,2.006204,2.047937,2.043367,2.039258,2.045996,2.070376,2.097082,2.112224,...,1.735016,1.731109,1.727900,1.728896,1.729304,1.726673,1.724738,1.723750,1.723889,1.726787
CW104SA0053,2.077128,2.040786,2.043095,2.071373,2.064174,2.076678,2.131703,2.123007,2.021653,1.929988,...,1.437869,1.437094,1.434376,1.433937,1.436358,1.438110,1.439149,1.439427,1.436281,1.432167

In [22]:
s = pd.read_csv('outputFiles/PCC1/aluminium.csv', engine='c', index_col=0)

Bad pipe message: %s [b'\xfa&\x07\xcd\xf2\xba\xaeB\xd7WY\xdfM25)a\xc2 \xe3\t\x8c\x85\xbb\xcc{\x0eL\xd0\xa0\xf6q{\xc2\xbeM\xd7H\xbc\xc6r[\xf1\xc9\xe2\x1ai\x9e\x03\xcd\x87\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06', b'\x07\x08']
Bad pipe message: %s [b'\t\x08\n\x08\x0b\x08\x04']
Bad pipe message: %s [b'\x08\x06\x04\x01\x05\x01\x06', b'']
Bad pipe message: %s [b'\x03\x02\x03\x04\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d\x00 t\xf1\xe9[\xf0\xd9}|\x9eV|\xbeV#\xfc\xc3\xc8`f(b?']
Bad pipe message: %s [b'\xdc\xd2\xde\\ZLu9]\xa4+!\xcb\xa7qp\xaft\x00\x00\xa6\xc0,\xc00\x00\xa3\x00\x9f\xcc\xa9\xcc\xa8\xcc\xaa\xc0\xaf\xc0\xad\xc0\xa3\xc0\x9f\xc0]\xc0a\xc0W\xc0S\xc0+\xc0/\x00\xa2\x00\x9e\xc0\xae\xc0\xac\xc0\xa2\xc0\x9e\xc0\\\xc0`\xc0V\xc0R\xc0$\xc0(\x00k\x00j\xc0s\xc0w\x00\xc4\x00\xc3\xc0']
Bad pipe message: %s [b"'\x00g\x00@\xc0r\xc0v\x00\xbe\x00\xbd\xc0\n\xc0\x14\x009\x008\x00\x88\x00\x87\xc0\t\xc0\x13\x003\x002\x00"]
Bad pipe message: %s [b'\x99\x00E\x00D\xc0\x07\xc0\x11\xc0\x08\xc0\x12\x00\x16\x00\x13\x00\x9d\xc0\xa1\xc0\x9d\xc0Q\x00\x9c\xc0\xa0\xc0\x9c\xc0P\x00=\x00\xc0\x00<\x00\xba\x005\x00\x84\x00/\x00\x96\x00A\x00\x05\x00\n\x00\xff\x01\x00\x00j\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x000\x00.\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0b\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x03\x03\x02\x03']
Bad pipe message: %s [b'\x02\x01', b'\x02\x02']
Bad pipe message: %s [b'\x05\x02\x06']
Bad pipe message: %s [b'SBWQ=\xff\xa2\xeb\xa1\x97R\x04\xd31\xd0\x9fi,\x00\x00\xa2\xc0\x14\xc0\n\x009\x008\x007\x006\x00\x88\x00\x87\x00\x86\x00\x85\xc0\x19\x00:\x00\x89\xc0\x0f\xc0\x05\x005\x00\x84\xc0\x13\xc0\t\x003\x002\x001\x000\x00\x9a\x00\x99\x00\x98\x00\x97\x00E\x00D\x00C\x00B\xc0\x18\x004\x00', b'F\xc0\x0e\xc0\x04\x00/\x00\x96\x00A\x00\x07\xc0\x11\xc0\x07\xc0\x16\x00\x18\xc0\x0c\xc0\x02\x00\x05\x00\x04\xc0\x12\xc0\x08\x00\x16\x00\x13\x00\x10\x00\r\xc0\x17\x00\x1b\xc0\r\xc0\x03\x00\n\x00\x15\x00\x12\x00\x0f\x00\x0c\x00\x1a\x00\t\x00\x14\x00\x11\x00\x19\x00\x08\x00\x06\x00\x17\x00\x03\xc0\x10\xc0\x06\xc0\x15\xc0\x0b\xc0\x01\x00\x02\x00\x01\x00\xff\x02\x01\x00\x00C\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x1c\x00\x1a\x00\x17\x00\x19\x00\x1c\x00\x1b\x00\x18\x00\x1a\x00\x16\x00\x0e\x00\r\x00\x0b\x00\x0c\x00\t']
Bad pipe message: %s [b'\x93\x95\xbb\xe9z\x8c\t@N\\\x92_\x19\xa4\x06\x1a\xdf\x81\x00\x00\xa2\xc0\x14\xc0\n\x009\x008\x007\x006\x00\x88\x00\x87\x00\x86\x00\x85\xc0\x19\x00:\x00\x89\xc0\x0f\xc0\x05\x005\x00\x84\xc0\x13\xc0\t\x003\x002\x001\x000\x00\x9a\x00\x99\x00\x98\x00\x97\x00E\x00D\x00C\x00B\xc0\x18\x004\x00\x9b\x00F\xc0']
Bad pipe message: %s [b'\x04\x00/\x00\x96\x00A\x00\x07\xc0\x11\xc0\x07']
Bad pipe message: %s [b'\xc2\xedy\xa5EW\x9cq%\xfe\xa9\x15\xcdT\xa7\xe5\xd5F\x00\x00>\xc0\x14\xc0\n\x009\x008\x007\x006']
Bad pipe message: %s [b'3\xd9\x1a\x12\xaa\xc8v\x88\xc8h\xf3\x1a\xeb\x1aE\xe2\xa4\xc1\x00\x00\x86\xc00\xc0,\xc0(\xc0$\xc0\x14\xc0\n\x00\xa5\x00\xa3\x00\xa1\x00\x9f']
Bad pipe message: %s [b"\xd3\xe2M\x88D~\xeb/W(yR\x15\xc1\x9em\xb8\xfd\x00\x00\xf4\xc00\xc0,\xc0(\xc0$\xc0\x14\xc0\n\x00\xa5\x00\xa3\x00\xa1\x00\x9f\x00k\x00j\x00i\x00h\x009\x008\x007\x006\x00\x88\x00\x87\x00\x86\x00\x85\xc0\x19\x00\xa7\x00m\x00:\x00\x89\xc02\xc0.\xc0*\xc0&\xc0\x0f\xc0\x05\x00\x9d\x00=\x005\x00\x84\xc0/\xc0+\xc0'\xc0#\xc0\x13\xc0\t\x00\xa4\x00\xa2\x00\xa0\x00\x9e\x00g\x00@\x00?\x00>\x003\x002\x001\x000\x00\x9a\x00\x99\x00\x98\x00\x97\x00E\x00D\x00C\x00B\xc0\x18\x00\xa6\x00l\x004\x00\x9b\x00F\xc01\xc0-\xc0)\xc0%\xc0\x0e\xc0\x04\x00\x9c\x00<\x00/\x00\x96\x00A\x00\x07\xc0\x11\xc0\x07\xc0\x16\x00\x18\xc0\x0c\xc0\x02\x00\x05\x00\x04\xc0\x12\xc0\x08\x00\x16\x00\x13\x00\x10\x00\r\xc0\x17"]

In [23]:
arr = [1,2,3,4,5,6,7]

In [25]:
result = [sum(arr[0:i]) for i in range(len(arr))]

In [26]:
result

[0, 1, 3, 6, 10, 15, 21]